### ISSUE TITLE
Set executable flag for bundled phpctags binary

### ISSUE THREAD

**Issue by mikehaertl** [vim-php/tagbar-phpctags.vim#5]
The `phpctags` binary from the vim.org package misses the executable flag. So after installation through a package manager like bundle I have to manuall fix this:

```
chmod a+x bundle/tagbar-phpctags/bin/phpctags
```

I think this can't be fixed in a `.zip` file, so maybe you can use a `.tgz` instead?

**Comment by InFog** [comment]
A bit late here... But the current version of phpctags already sets the correct permission. Since we are building it after the download everything is fine.
