### ISSUE TITLE
Fails on Vim for Windows

### ISSUE THREAD

**Issue by bogota** [vim-php/tagbar-phpctags.vim#8]
Is there anyone using tagbar-phpctags.vim on Windows?

I just got its distributed archive at vim.org and gave it a try on Windows version of gVim 7.4, but with no success. When I did :TagbarToggle for a php script, gVim spewed the following messages.

```
Error detected while processing function tagbar#ToggleWindow..<SNR>46_ToggleWindow..<SNR>46_OpenWIndow..<SNR>46_AutoUpdate..<SNR>46_ProcessFile..<SNR>46_EcecuteCtagsOnFile:
line   64:
Tagbar: Could not execute ctags for c:\tmp\VIBE8C8.tmp.php!
Executed command: "phpctags  --memory="128M" -f -  "c:\tmp\VIBE8C8.tmp.php""
Command output:
'phpctags' is not recognized as an internal or external command,
operable program or batch file.
```

Obviously Windows could not handle phpctags rightly. I've confirmed the command `php phpctags -f - some_script.php` works flawlessly on cmd.exe, writing down results to stdout. But I don't know the way to run tagbar-phpctags.vim without tweaking something.

**Comment by bogota** [comment]
Solved by myself.  The script came to work after making [phpctags.cmd](https://gist.github.com/bogota/0aeff3bf087d7f963788) and copying it in the same folder as phpctags.

**Comment by InFog** [comment]
Good one, @bogota. Yes, you need phpctags in your path for it to work. The plugins does its best to install and use it, but I have no idea if it works on Windows or not, Linux user here.
