### ISSUE TITLE
xdebug related performance loss

### ISSUE THREAD

**Issue by klaernie** [vim-php/tagbar-phpctags.vim#9]
While it is not noticeable with smaller files, on big class files I found that having xdebug enabled slows down phpctags extremely, to the point where saving a file costs 15 seconds.

Please support disabling xdebug from inside phpctags.

**Comment by InFog** [comment]
Thank you, @klaernie. Please, open an issue on https://github.com/vim-php/phpctags.

Just out of curiosity... How big are the files?

(I'm closing this one since it's not an issue on the tagbar itself)
